# Generated by Django 4.2.20 on 2025-04-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_account_name_alter_customuser_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ewasteorganizationrepresentative',
            name='customuser_ptr',
        ),
        migrations.RemoveField(
            model_name='ewasteorganizationrepresentative',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='universitycommunitymember',
            name='customuser_ptr',
        ),
        migrations.RemoveField(
            model_name='universitycommunitymember',
            name='university',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='EwasteOrganization',
        ),
        migrations.DeleteModel(
            name='EwasteOrganizationRepresentative',
        ),
        migrations.DeleteModel(
            name='University',
        ),
        migrations.DeleteModel(
            name='UniversityCommunityMember',
        ),
    ]
