# Generated by Django 4.2.20 on 2025-04-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste_management', '0004_alter_topic_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='description',
            new_name='content',
        ),
    ]
