# Generated by Django 4.2.20 on 2025-04-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste_management', '0005_rename_description_topic_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_detail',
            new_name='content',
        ),
    ]
