# Generated by Django 4.2.20 on 2025-04-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste_management', '0006_rename_comment_detail_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incentiveredemptionrecord',
            old_name='points_used',
            new_name='quantity',
        ),
    ]
