# Generated by Django 4.2.20 on 2025-04-14 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste_management', '0007_rename_points_used_incentiveredemptionrecord_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations_requested', to=settings.AUTH_USER_MODEL),
        ),
    ]
