# Generated by Django 4.2.20 on 2025-04-14 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste_management', '0009_alter_consultation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastecollection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waste_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
