# Generated by Django 4.2.20 on 2025-04-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste_management', '0010_alter_wastecollection_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='publication_date',
        ),
        migrations.AlterField(
            model_name='wastecollection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
