# Generated by Django 4.2.20 on 2025-04-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste_management', '0011_remove_publication_publication_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='duration_hr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consultation',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
