# Generated by Django 4.2.20 on 2025-04-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste_management', '0013_alter_consultation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('university_community', 'University_Community'), ('campus_expert', 'Campus_Expert'), ('collection_team', 'Collection_Team'), ('processing_team', 'Processing_Team'), ('recycling_team', 'Recycling_Team')], max_length=20),
        ),
    ]
