# Generated by Django 4.2.20 on 2025-04-27 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste_management', '0014_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCollectionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('collected', 'Collected')], default='pending', max_length=20)),
                ('points_earned', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_collection_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WasteCollectionBooking',
                'verbose_name_plural': 'WasteCollectionBookings',
            },
        ),
        migrations.CreateModel(
            name='WasteCollectionSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In_Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('collection_date_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_collections', to='ewaste_management.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waste_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WasteCollection',
                'verbose_name_plural': 'WasteCollections',
            },
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='waste_collection',
        ),
        migrations.DeleteModel(
            name='WasteCollection',
        ),
        migrations.AddField(
            model_name='wastecollectionbooking',
            name='waste_collection_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='ewaste_management.wastecollectionslot'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='waste_collection_booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to='ewaste_management.wastecollectionbooking'),
            preserve_default=False,
        ),
    ]
