# Generated by Django 4.2.20 on 2025-04-27 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste_management', '0015_wastecollectionbooking_wastecollectionslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='event_end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='event_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
