# Generated by Django 4.2.20 on 2025-04-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste_management', '0016_publication_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='component',
            name='status',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
