# Generated by Django 4.2.20 on 2025-04-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste_management', '0017_component_amount_component_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastecollectionslot',
            name='user',
        ),
    ]
