# Generated by Django 4.2.20 on 2025-04-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste_management', '0019_wastecollectionslot_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('collection', 'Collection'), ('processing', 'Processing'), ('recycling', 'Recycling')], default='processing', max_length=20),
            preserve_default=False,
        ),
    ]
