# Generated by Django 4.2.20 on 2025-04-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste_management', '0020_organization_organization_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementrecord',
            name='recipeint_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movementrecord',
            name='recipeint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recieved', to='ewaste_management.organization'),
        ),
    ]
