# Generated by Django 4.2.20 on 2025-04-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste_management', '0022_user_point_earned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('university_community', 'University_Community'), ('campus_expert', 'Campus_Expert'), ('organization_team', 'Organization_Team')], max_length=20),
        ),
    ]
