# Generated by Django 4.2.20 on 2025-04-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste_management', '0023_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecollectionbooking',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
