# Generated by Django 4.2.20 on 2025-05-01 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste_management', '0024_wastecollectionbooking_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentiveredemptionrecord',
            name='redemption_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wastecollectionslot',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('edited', 'Edited'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
