# Generated by Django 4.2.20 on 2025-05-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste_management', '0025_alter_incentiveredemptionrecord_redemption_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='duration_hr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
