# Generated by Django 4.2.20 on 2025-05-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste_management', '0026_alter_consultation_duration_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecollectionbooking',
            name='preferrable_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wastecollectionbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('collected', 'Collected'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
