# Generated by Django 4.2.20 on 2025-05-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste_management', '0027_wastecollectionbooking_preferrable_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastecollectionbooking',
            name='preferrable_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
