from django.urls import path
from django.conf.urls import handler403, handler400

from . import views

app_name = "ewaste_management"
urlpatterns = [
    path("", views.index, name="index"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("incentives/", views.incentives, name="incentives"),
    path("incentives/edit/<int:incentive_id>/", views.edit_incentive, name="edit_incentive"),
    path("incentives/delete/<int:incentive_id>/", views.delete_incentive, name="delete_incentive"),
    path("incentives/add", views.add_incentive, name="add_incentive"),
    path("accounts/", views.accounts, name="accounts"),
    path("accounts/<str:account_username>/", views.account, name="account"),
    path("accounts/<str:account_username>/alter_status", views.account_action, name="account_action"),
    path("ces/", views.ces, name="ces"),
    path("ces/<int:ce_id>", views.ce, name="ce"),
    path("ces/approve/<int:ce_id>", views.approve_ce, name="approve_ce"),
    path("ces/reject/<int:ce_id>", views.reject_ce, name="reject_ce"),
    path("log/", views.log_details, name="log"),
    path("forum/", views.forum, name="forum"),
    path("forum/<int:topic_id>/", views.view_topic, name="topic"),
    path("forum/edit/<int:topic_id>/", views.edit_topic, name="edit_topic"),
    path("forum/add/", views.add_topic, name="add_topic"),
    path("forum/add/<int:topic_id>/", views.add_comment, name="add_comment"),
    path("forum/edit/<int:topic_id>/<int:comment_id>/", views.edit_comment, name="edit_comment"),
    path("uemip/", views.uemip, name="uemip"),
    path("uemip/<int:publication_id>", views.view_publication, name="uemip"),
    path("uemip/universities/", views.universities_profile, name="universities_profile"),
    path("uemip/university/<int:university_id>", views.university_profile, name="university_profile"),
    path("profile/", views.profile, name="profile"),
    path("profile/edit", views.edit_profile, name="edit_profile"),
    path("ce_application/", views.ce_application, name="ce_application"),
    path("ce_application/submit", views.submit_ce_application, name="submit_ce_application"),
    path("incentives/<int:incentive_id>/redeem/", views.redeem_incentive, name="redeem_incentive"),
    path("consultations/", views.consultations, name="consultations"),
    path("consultations/book/", views.consultation, name="consultation"),
    path("consultations/<int:consultation_id>/book", views.book_consultation, name="book_consultation"),
    path("pickup/", views.pickup, name="pickup"),
    path("pickup/book/<int:pickup_id>", views.pickup_detail, name="pickup_detail"),
    path("pickup/book", views.book_pickup, name="book_pickup"),
    path("pickup/summary/", views.pickup_summary, name='pickup_summary'),
    path("forum/delete/<int:topic_id>/", views.delete_topic, name="delete_topic"),
    path("forum/delete/<int:topic_id>/<int:comment_id>/", views.delete_comment, name="delete_comment"),
    path("uemip/add/", views.add_publication, name="add_publication"),
    path("uemip/edit/<int:publication_id>/", views.edit_publication, name="edit_publication"),
    path("uemip/university_profile/add/", views.add_university_profile, name="add_university_profile"),
    path("uemip/university_profile/edit/<int:university_id>/", views.edit_university_profile, name="edit_university_profile"),
    path("consultations/add/", views.add_consultation, name="add_consultation"),
    path("consultations/edit/<int:consultation_id>/", views.edit_consultation, name="edit_consultation"),
    path("pickup/schedule/", views.schedule_pickup, name="schedule_pickup"),
    path("pickup/edit/<int:pickup_id>/", views.edit_pickup, name="edit_pickup"),
    path("pickup/delete/<int:pickup_id>/", views.delete_pickup, name="delete_pickup"),
    path("views/", views.views, name="views"),
    path("track/", views.track, name="track"),
    path("track/add/", views.add_track, name="add_track"),
    path("organization/profile/edit/", views.edit_organization_profile, name="edit_org_profile"),
    path("organization/profile/", views.organization_profile, name="organization_profile"),
    path("pickup/summary/past/", views.past_pickup_summary, name='past_pickup_summary'),  
    path("forum/all", views.all_topics, name="all_topics"),
    path("forum/all/me", views.user_created_topics, name="user_created_topics"),
    path("consultations/cancel/<int:consultation_id>/", views.cancel_consultation, name="cancel_consultation"),  
    path("organizations/profiles/", views.organization_profiles, name="organization_profiles"),
    path("pickup/cancel/<int:pickup_id>/", views.cancel_pickup, name="cancel_pickup"),
    path("pickup/confirm/<int:pickup_id>/", views.confirm_pickup, name="confirm_pickup"),
    path("pickup/reject/<int:pickup_id>/", views.reject_pickup, name="reject_pickup"),
    path("pickup/collected/<int:pickup_id>/", views.collected_pickup, name="collected_pickup"),
    path("pickup/view_pickup/<int:booking_id>", views.view_pickup, name="view_pickup"),
    path("accounts/demote/<str:account_username>/", views.demote_account, name="demote_account"),
    path("pickup/search/", views.search_pickup, name="search_pickup"),
    path("pickup/my_appointments/", views.my_appointments, name="my_appointments")
    ]


handler403 = views.custom_403
handler400 = views.custom_400